name: BETA - Build myclub App and Deploy on Firebase Hosting
on:
  push:
    branches:
      - beta
jobs:
  build_beta:
    name: Build & Deploy BETA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Config Node Version because of npm login issues.
        uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: Build (BETA)
        run: npm run build:beta
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:beta
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
