name: PROD - Build myclub App and Deploy on Firebase Hosting
on:
  push:
    branches:
      - master
jobs:
  build_default:
    name: Build & Deploy Default Unihockey App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build (Default Unihockey)
        run: npm run build:prod
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:app-unihockey
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  build_kadetten:
    needs: build_default
    name: Build & Deploy Kadetten Unihockey App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Build app-kadetten-unihockey
        run: npm run build:app-kadetten-unihockey
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:app-kadetten-unihockey
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  build_uhc_winu:
    needs: [build_default, build_kadetten]
    name: Build & Deploy UHC Winterthur United App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Build app-uhc-win-u
        run: npm run build:app-uhc-win-u
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:app-uhc-win-u
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
